### ISSUE TITLE
Hangout Web View vs. Chrome PlugIn View

### ISSUE THREAD

**Issue by l-i-n-k** [meetfranz/recipe-hangouts#2]
I appreciate the Web version for the visual style but the PlugIn Hangout gives me more space to read and answer chats. 
Could this be a possible alternative view? 

![2017-10-26_10-32-13](https://user-images.githubusercontent.com/784287/32043293-a5e4079a-ba3a-11e7-8775-3dfa6f3f381d.png)

**Comment by gcarrion-gfrmedia** [comment]
I also prefer the Chrome extension appearance, but not sure if that is possible. Maybe @adlk could let us know.

**Comment by adlk** [comment]
I took a look at the chrome extension and unfortunately it's not easily possible. However, Hangouts is quite under pressure by Slack, Microsoft Teams, Stride, ... and there is a new version of hangouts/chat coming which is in EAP right now: https://gsuite.google.com/campaigns/index__chateap.html

At this point I hope they it will come sooner than later and replace hangouts as it is right now.
