### ISSUE TITLE
Suggestion: YakYak integration

### ISSUE THREAD

**Issue by kecinzer** [meetfranz/recipe-hangouts#6]
I realy like Franz, but I also very like YakYak client for Hangouts. Will be possible to integrate YakYak into Frnaz instead of use native Hangouts UX?

**Comment by metalbote** [comment]
+1

**Comment by RazZziel** [comment]
+1!

**Comment by closingin** [comment]
Hello @kecinzer , you're on the wrong repository but anyway. YakYak is a desktop application, whereas Franz is only meant to display web pages so this isn't possible.

Can you close your issue please ? :slightly_smiling_face:
